sampleInput = "GTATAGACGCGGTGGCGTTCGGAAGGGCAGCTTCCCTGATTACCTCCGTGGTGCTAAAAGCGGTCTTCTGAGCTTTAATCTAACCTTAGCATGCTGTTGAGATTTCCGAACGTAGCGACTCGCCTGTCAACCGTGCCCTGGGTCGCTCCGACGTCAGTGTAATTGATCTTCTTATTCACGGCCTTCATTACGACGACAAGGCCGAGGACCGAACTCATAAAATGTTAGCCCGTCTGCACCGGCGGATCTATAGCGAGCTTGCCTCAGATCGAAGCTCTTTATTACACTTCGTACTACCAGCTTGCTTGAATCCTTTGACGACGGGGGCCGGTATTGAGCAGCAGAATGCTTACAGAAAGGAGAAACGAGTCATTAGCCCATCCCGAAGAAAGTTTTTGGGTGGGGGACGGCACCAGCCACGTATGAGGGTATGGAGGCAGGTGTCTCGTCGGCAACTGCGGTTGGGCCCGAAAGCCTGTACAGTCCATTTGGCGTATTGAACTCCATACTCTCCGGGTTTAGCTATGTATCCAGCGTTATATATACGGTCGACGTCGGTCCGCCTTAGGGGTTACCATTGAATCCGGCATTACGCTAGGCGGGCTTCACTAGTAAGAAAATATACGACAAATAGGTCTAGCGGACTCCAATCCCGTTACTGGTTCTACGAGCGTCTTTTCAAACCTGGAGCATTCCCGTATCCGACGTCGCCTGGCCCTCTGCGGACCACCACTGTGGATCGCTTAGACACTTGACCAGGGGCGGGTGGCCATGTTTCTCCGAACTCACAGCCGATGCTCTAAAGGACACGGCAGATATTTCAGATTAGTGTGTTACGTTTGCGCGAGCCTGACTGCCCATGATCAGACCCTTCGAGCTCCTAAATCTTACCAGCGAAGT"

aCount = 0
gCount = 0
tCount = 0
cCount = 0

for letter in sampleInput:
    if letter == "A":
        aCount += 1
    elif letter == "G":
        gCount += 1
    elif letter == "T":
        tCount += 1
    elif letter == "C":
        cCount += 1

print("{} {} {} {}".format(aCount,cCount,gCount,tCount))