sampleInput = "ATAGATATCGCGCCGAGAGGGCCTGCCACTTGCTGAGGCTTACGGGCCGCCGGTTTATTCTAGGGACCGCGGCATTGAGTGAGCTTCCAGAACTGCTAACTCAATAAGCTGCGACTCCGACAATGGAATTGCGTTCCACGAATGACTTCCAGTCTTAAGTGGTTTTGCACAGTCTTGAGTTGGACCCTTAACGTGTTAAGCAGTATATATCACTGGGGTAAAACCTGCAACTAAGCTGTCCACGAGTCACTGCAGTCCTGTAAAACTGGTCACGCGGTTTAGTAGAGGAGGGTTGTATCATCTGCCTTTTATGTCCGGAAATTACGAAGGGCCGATTGGCGGCCAACCCCAGCTTTACGGCACTGTCCATTTTATGCTCTAATCTTAGCTTGGGTCTAATAGATTCTGCACTTCAAGTTAGTCAACACCCTATACTGTCATAGGTGAAGCAATCTCTACAAACCGCCCTGCATCGTGAAACCGAAATTTCGACTAACTTACAACGAAACGTAGTTGTTAGGTCTCACGGGGTCATTATACTGCACAACACTGGACGGGGGAACGATGTAGAGTAGGGGAGTCAGAAACTAAGCGAATCTGAACTCGGAAAACTGCGTAAAGGTAAGCGCTTTGAAAGAGTGGGCACCTGAGGGTTTTTGTGACGAGTAGCCGCTCTTAATGGATCGAACCGAACTGATCATGATTGGTCGCACTGTGGAGACATAATAAAGGAACTGTGGCCTCCTGGATGCACGCTCCAGTAAATCGCAGGTATCAACTAAGGGATTGTGCCCGAGCCATCTTCTGAACGCCTCGCAGGTGTCAGACGCCGTTCACTGAACATTTGTGGTCGTCGCTCAGGGATTCGCCCGAGCGCGTTTAACCTAACACAGCGCTGACAGTTGATTCCCCCATATAGCCAGTGTGTACAATGTCACTGCTCCCGAGCACTACCGAG"

complement = ""

for letter in sampleInput:
    if(letter == "A"):
        complement += "T"
    elif letter == "T":
        complement += "A"
    elif letter == "C":
        complement += "G"
    elif letter == "G":
        complement += "C"

print complement[::-1]
